// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkx3DxjHAeDRjWfLj3KDtHMnysQJ8qrqc',
    appId: '1:537381237768:web:c868dbd1853e8ceefc4dbd',
    messagingSenderId: '537381237768',
    projectId: 'f1pass-48a99',
    authDomain: 'f1pass-48a99.firebaseapp.com',
    storageBucket: 'f1pass-48a99.firebasestorage.app',
    measurementId: 'G-3ZY8N667CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GzLxKDPqMSMkRcGt9RuUkOEmmOnAaRw',
    appId: '1:537381237768:android:35e9f8d45e9dd505fc4dbd',
    messagingSenderId: '537381237768',
    projectId: 'f1pass-48a99',
    storageBucket: 'f1pass-48a99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7eu3FE_PA0XwpSk2AQlnWzOFQj7EDaM',
    appId: '1:537381237768:ios:8b88a4ba0c3d6cc9fc4dbd',
    messagingSenderId: '537381237768',
    projectId: 'f1pass-48a99',
    storageBucket: 'f1pass-48a99.firebasestorage.app',
    iosBundleId: 'com.example.f1pass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy7eu3FE_PA0XwpSk2AQlnWzOFQj7EDaM',
    appId: '1:537381237768:ios:8b88a4ba0c3d6cc9fc4dbd',
    messagingSenderId: '537381237768',
    projectId: 'f1pass-48a99',
    storageBucket: 'f1pass-48a99.firebasestorage.app',
    iosBundleId: 'com.example.f1pass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkx3DxjHAeDRjWfLj3KDtHMnysQJ8qrqc',
    appId: '1:537381237768:web:0ad6616d554fe6cefc4dbd',
    messagingSenderId: '537381237768',
    projectId: 'f1pass-48a99',
    authDomain: 'f1pass-48a99.firebaseapp.com',
    storageBucket: 'f1pass-48a99.firebasestorage.app',
    measurementId: 'G-64QS0BB4XL',
  );
}
